CREATE USER IF NOT EXISTS 'vt_dba'@'%'
    IDENTIFIED WITH 'mysql_native_password' AS '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29';
GRANT ALL 
    ON *.* TO 'vt_dba'@'%';
GRANT GRANT OPTION 
    ON *.* TO 'vt_dba'@'%';

CREATE USER IF NOT EXISTS 'vt_app'@'%'
    IDENTIFIED WITH 'mysql_native_password' AS '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, FILE,
        REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES,
        LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW,
        SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
    ON *.* TO 'vt_app'@'%';

CREATE USER IF NOT EXISTS 'vt_appdebug'@'%'
    IDENTIFIED WITH 'mysql_native_password' AS '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29';
GRANT SELECT, SHOW DATABASES, PROCESS
    ON *.* TO 'vt_appdebug'@'%';

CREATE USER IF NOT EXISTS 'vt_allprivs'@'%'
    IDENTIFIED WITH 'mysql_native_password' AS '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP,RELOAD, PROCESS, FILE,
        REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES,
        LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW,
        SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
    ON *.* TO 'vt_allprivs'@'%';

CREATE USER IF NOT EXISTS 'vt_filtered'@'%'
    IDENTIFIED WITH 'mysql_native_password' AS '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, FILE,
        REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES,
        LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW,
        SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
    ON *.* TO 'vt_filtered'@'%';

CREATE USER IF NOT EXISTS 'vt_orc_client'@'%'
    IDENTIFIED WITH 'mysql_native_password' AS '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29';
GRANT SUPER, PROCESS, REPLICATION SLAVE, RELOAD
    ON *.* TO 'vt_orc_client'@'%';
GRANT SELECT
    ON _vt.* TO 'vt_orc_client'@'%';

CREATE USER IF NOT EXISTS 'repli'@'%'
    IDENTIFIED WITH 'mysql_native_password' AS '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29';
GRANT SUPER, PROCESS, REPLICATION SLAVE, RELOAD
    ON *.* TO 'repli'@'%';

CREATE USER IF NOT EXISTS 'test-ro'@'%'
    IDENTIFIED WITH 'mysql_native_password' AS '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29';
GRANT SELECT
    ON *.* TO 'test-ro'@'%';

CREATE USER IF NOT EXISTS 'test-rw'@'%'
    IDENTIFIED WITH 'mysql_native_password' AS '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29';
GRANT CREATE, DELETE, FILE, INSERT, REPLICATION CLIENT, SELECT, UPDATE
    ON *.* TO 'test-rw'@'%';
