CREATE DATABASE etsy_payments_shard_001_0_A;
USE etsy_payments_shard_001_0_A;

CREATE TABLE `account_updater_batches` (
  `account_updater_batch_id` bigint unsigned NOT NULL,
  `account_updater_job_id` bigint unsigned NOT NULL,
  `filename_base` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Unique string used as base of various related files exchanged with PSP',
  `batch_file_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'See GCI_PaymentGateway_Adyen_AccountUpdater_BatchStatus',
  `process_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'See GCI_StateMachine_ProcessStatus',
  `retry_count` int unsigned DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`account_updater_job_id`,`account_updater_batch_id`),
  UNIQUE KEY `account_updater_batch_id` (`account_updater_batch_id`),
  KEY `filename_base` (`filename_base`),
  KEY `update_date` (`update_date`),
  KEY `create_date` (`create_date`),
  KEY `batch_file_status` (`batch_file_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `account_updater_items` (
  `account_updater_item_id` bigint unsigned NOT NULL,
  `account_updater_batch_id` bigint unsigned NOT NULL,
  `card_id` bigint unsigned NOT NULL,
  `ucc_token` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Adyen token associated with card',
  `shopper_reference` bigint unsigned NOT NULL COMMENT 'Unique identifier we provide to Adyen updater: cardholder user_id',
  `mid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Merchant identifier associated with card',
  `transaction_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Cached Adyen response field',
  `action_result` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Cached Adyen response field: actual update result from card scheme',
  `refusal_reason` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Cached Adyen response field: reason/error when card is not submitted per scheme_submission_status',
  `scheme_submission_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Cached Adyen response field: whether card was submitted to scheme. See refusal_reason if not submitted',
  `scheme_processed_date` int unsigned DEFAULT NULL COMMENT 'Cached Adyen response field',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `item_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Used by state machine to manage processing of record. See GCI_PaymentGateway_Adyen_AccountUpdater_ItemStatus',
  `process_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Used by state machine to manage processing of record. See GCI_StateMachine_ProcessStatus',
  `new_alias` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Cached Adyen response field',
  `new_expiry_month` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Cached Adyen response field',
  `new_expiry_year` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Cached Adyen response field',
  PRIMARY KEY (`account_updater_batch_id`,`account_updater_item_id`),
  UNIQUE KEY `account_updater_item_id` (`account_updater_item_id`),
  KEY `card_id` (`card_id`),
  KEY `ucc_token` (`ucc_token`),
  KEY `shopper_reference` (`shopper_reference`),
  KEY `update_date` (`update_date`),
  KEY `create_date` (`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `account_updater_jobs` (
  `account_updater_job_id` bigint unsigned NOT NULL,
  `population_table_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'The name of the rollup table to query as part of the savePopulation method in the AccountUpdaterJobProcessor',
  `job_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Used by state machine to manage processing of record. See GCI_PaymentGateway_Adyen_AccountUpdater_JobStatus',
  `process_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Used by state machine to manage processing of record. See GCI_StateMachine_ProcessStatus',
  `batch_count` int unsigned DEFAULT NULL,
  `item_count` int unsigned DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `environment` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `next_process_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_updater_job_id`),
  KEY `job_status` (`job_status`),
  KEY `update_date` (`update_date`),
  KEY `create_date` (`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `bank_account_verification_tracker` (
  `bank_account_verification_tracker_id` bigint unsigned NOT NULL,
  `shop_id` bigint unsigned NOT NULL,
  `start_date` int unsigned NOT NULL COMMENT 'Bank verification start date',
  `end_date` int unsigned DEFAULT NULL COMMENT 'Bank verification end date',
  `verification_status` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, COMPLETED, ABORTED',
  `group_identifier` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Identifier when shop is part of a group (if applicable)',
  `verification_method` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'PLAID, MICRO_DEPOSITS, BANK_STATEMENTS',
  `verification_method_start_date` int unsigned DEFAULT NULL COMMENT 'Active bank verification method start date',
  `bank_account_id` bigint unsigned DEFAULT NULL COMMENT 'ID of the Bank Account verified',
  `shop_lock_start_date` int unsigned DEFAULT NULL,
  `shop_lock_end_date` int unsigned DEFAULT NULL,
  `has_shop_lock` tinyint NOT NULL DEFAULT '0',
  `disbursement_hold_start_date` int unsigned DEFAULT NULL,
  `disbursement_hold_end_date` int unsigned DEFAULT NULL,
  `has_disbursement_hold` tinyint NOT NULL DEFAULT '0',
  `aborted_date` int unsigned DEFAULT NULL,
  `aborted_reason` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `aborted_actor` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bank_statement_failure_count` int unsigned NOT NULL DEFAULT '0',
  `failed_verification_attempts` int unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`shop_id`,`bank_account_verification_tracker_id`),
  UNIQUE KEY `bank_account_verification_tracker_id` (`bank_account_verification_tracker_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `bank_account_verification_tracker_log` (
  `bank_account_verification_tracker_log_id` bigint unsigned NOT NULL,
  `bank_account_verification_tracker_id` bigint unsigned NOT NULL,
  `shop_id` bigint unsigned NOT NULL,
  `identifier` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'plaid, micro_deposits, bank_statements, look_back, name_match, ...',
  `identifier_id` bigint unsigned DEFAULT NULL COMMENT 'Any ID related to the identifier (plaid session id, micro deposits id, look back id...)',
  `event` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'A system-defined keyword to represent the event tracked',
  `event_value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Additional information related to event (error code, webhook_code, etc…)',
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'event description (if applicable)',
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`shop_id`,`bank_account_verification_tracker_log_id`),
  UNIQUE KEY `bank_account_verification_tracker_log_id` (`bank_account_verification_tracker_log_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `billing_payments` (
  `billing_payment_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL DEFAULT '0',
  `card_id` bigint unsigned NOT NULL DEFAULT '0',
  `amount` int NOT NULL DEFAULT '0',
  `currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `process_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `next_process_date` int unsigned NOT NULL DEFAULT '0',
  `state_retry_count` int unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  `environment` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `payment_method` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `billing_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `vpa` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `ip_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`billing_payment_id`),
  KEY `card_id_idx` (`card_id`),
  KEY `create_date_idx` (`create_date`),
  KEY `update_date_idx` (`update_date`),
  KEY `environment_idx` (`environment`),
  KEY `process_status_idx` (`process_status`,`environment`,`update_date`),
  KEY `user_status_idx` (`user_id`,`status`,`create_date`),
  KEY `currency_create_date_idx` (`currency`,`create_date`),
  KEY `currency_status_idx` (`currency`,`status`,`process_status`),
  KEY `status_process_update_date_idx` (`status`,`process_status`,`environment`,`next_process_date`,`update_date`),
  KEY `billing_type_idx` (`billing_type`),
  KEY `vpa_idx` (`vpa`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `billing_payments_adjustments` (
  `billing_payment_adjustment_id` bigint unsigned NOT NULL,
  `billing_payment_id` bigint unsigned NOT NULL DEFAULT '0',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `process_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `total_adjustment_amount` int NOT NULL DEFAULT '0',
  `next_process_date` int unsigned NOT NULL DEFAULT '0',
  `state_retry_count` int unsigned NOT NULL DEFAULT '0',
  `environment` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'production',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  `user_id` bigint unsigned NOT NULL DEFAULT '0',
  `reason_text` mediumtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`billing_payment_adjustment_id`),
  KEY `billing_payment_id` (`billing_payment_id`,`create_date`),
  KEY `create_date` (`create_date`),
  KEY `user_id` (`user_id`,`create_date`),
  KEY `process_status` (`process_status`,`environment`,`update_date`),
  KEY `next_process_date` (`status`,`process_status`,`environment`,`next_process_date`,`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `cc_txns` (
  `cc_txn_id` bigint unsigned NOT NULL,
  `txn_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'payment, adjustment, recoupment',
  `reference_id` bigint unsigned NOT NULL COMMENT 'payment_id, payment_adjustment_id, recoupment_id',
  `instrument_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'credit card or gift card',
  `instrument_id` bigint unsigned NOT NULL COMMENT 'either a credit card id or giftcard id',
  `amount` int NOT NULL,
  `currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `auth_response_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `settle_response_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `auth_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `arn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `avs_address_response` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'address portion of avs response from the cc gateway',
  `shop_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_token` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_type` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_on_card` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_num_head` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_num_tail` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_exp_month` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_exp_year` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_addr_first_line` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_addr_second_line` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_addr_city` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_addr_state` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_addr_zip` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `iso_country_code` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reader_serial_num` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `original_ref_id` bigint unsigned DEFAULT NULL,
  `payment_gateway` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'worldpay',
  `giftcard_deduction_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `execute_3d` tinyint DEFAULT '0',
  `processor_mid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `payin_entity` varchar(48) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `settlement_entity` varchar(48) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`cc_txn_id`),
  KEY `reference_id` (`reference_id`,`txn_type`,`create_date`),
  KEY `reference_id_2` (`reference_id`,`txn_type`,`instrument_type`,`instrument_id`),
  KEY `txn_type` (`txn_type`,`instrument_id`,`instrument_type`),
  KEY `status` (`status`,`create_date`),
  KEY `create_date` (`create_date`),
  KEY `card_exp_month_year` (`card_exp_year`,`card_exp_month`,`create_date`),
  KEY `last_four_exp_date` (`card_num_tail`,`card_exp_year`,`card_exp_month`,`create_date`),
  KEY `last_four_create_date` (`card_num_tail`,`create_date`),
  KEY `last_four_name_on_card` (`card_num_tail`,`name_on_card`(191),`create_date`),
  KEY `last_four_card_addr_zip` (`card_num_tail`,`card_addr_zip`(191),`create_date`),
  KEY `name_on_card` (`name_on_card`(191),`create_date`),
  KEY `card_addr_zip` (`card_addr_zip`(191),`create_date`),
  KEY `amount` (`amount`,`create_date`),
  KEY `update_date_idx` (`update_date`),
  KEY `card_token` (`card_token`,`create_date`),
  KEY `cardnumtail_amt_crr_createdate` (`card_num_tail`,`amount`,`currency`,`create_date`),
  KEY `payment_gateway_create_date_idx` (`payment_gateway`,`create_date`),
  KEY `cardnumhead_createdate` (`card_num_head`,`create_date`),
  KEY `txn_type_instrument_type_id` (`txn_type`,`instrument_type`,`instrument_id`,`amount`,`update_date`),
  KEY `processor_mid_create_date_idx` (`processor_mid`,`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `cdc_etet` (
  `id` bigint unsigned NOT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `f_varchar` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `debezium_signal` (
  `id` varchar(42) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `data` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8 COMMENT='Used only to send signals to Debezium';

CREATE TABLE `disregarded_entity_shops` (
  `disregarded_entity_id` bigint unsigned NOT NULL,
  `shop_id` bigint unsigned NOT NULL,
  `tax_year` int unsigned NOT NULL,
  `is_disregarded_entity` tinyint NOT NULL DEFAULT '0',
  `business_taxpayer_id_token` bigint unsigned DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`shop_id`,`disregarded_entity_id`),
  UNIQUE KEY `disregarded_entity_id` (`disregarded_entity_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `donation_payments` (
  `donation_payment_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `payment_id` bigint unsigned NOT NULL,
  `amount` bigint unsigned NOT NULL,
  `charity_mid` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `process_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `next_process_date` int unsigned NOT NULL,
  `state_retry_count` int unsigned DEFAULT NULL,
  `environment` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`donation_payment_id`),
  KEY `payment_id` (`payment_id`),
  KEY `pstatus_status_udate_env` (`process_status`,`status`,`update_date`,`environment`),
  KEY `user_id_status` (`user_id`,`status`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `status_pstatus_cdate_env` (`status`,`process_status`,`create_date`,`environment`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `feature_log` (
  `log_id` bigint unsigned NOT NULL,
  `shop_id` bigint unsigned NOT NULL,
  `flag_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `flag_value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `additional_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `create_date` int NOT NULL,
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`log_id`),
  KEY `flag_name_idx` (`flag_name`),
  KEY `create_date_idx` (`create_date`),
  KEY `update_date_idx` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `fraud_requests` (
  `request_id` bigint unsigned NOT NULL,
  `group_payment_id` bigint unsigned NOT NULL,
  `receipt_id` bigint unsigned DEFAULT NULL,
  `user_id` bigint unsigned NOT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`request_id`,`create_date`),
  KEY `user_group_payment_receipt_index` (`user_id`,`group_payment_id`,`receipt_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `fraud_responses` (
  `response_id` bigint unsigned NOT NULL,
  `payment_id` bigint unsigned NOT NULL DEFAULT '0',
  `receipt_id` bigint unsigned DEFAULT NULL,
  `crossreference` text NOT NULL,
  `rules_tripped` text NOT NULL,
  `total_score` int NOT NULL,
  `recommendation_code` text NOT NULL,
  `remarks` longtext NOT NULL,
  `review_response` varchar(255) DEFAULT NULL,
  `iovation_id` bigint unsigned DEFAULT NULL,
  `iovation_first_seen_date` int unsigned DEFAULT NULL,
  `iovation_flash_enabled` tinyint unsigned NOT NULL DEFAULT '0',
  `iovation_flash_installed` tinyint unsigned NOT NULL DEFAULT '0',
  `iovation_flash_storage_enabled` tinyint unsigned NOT NULL DEFAULT '0',
  `iovation_flash_version` varchar(255) DEFAULT NULL,
  `iovation_js_enabled` tinyint unsigned NOT NULL DEFAULT '0',
  `iovation_error` varchar(255) DEFAULT NULL,
  `iovation_real_ip` varchar(255) DEFAULT NULL,
  `iovation_real_ip_country_code` varchar(255) DEFAULT NULL,
  `iovation_real_ip_isp` varchar(255) DEFAULT NULL,
  `iovation_real_ip_org` varchar(255) DEFAULT NULL,
  `iovation_reason` varchar(255) DEFAULT NULL,
  `iovation_result` varchar(255) DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`payment_id`,`response_id`),
  UNIQUE KEY `response_id_unique` (`response_id`),
  KEY `receipt_id` (`receipt_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `response_payment_receipt_index` (`response_id`,`payment_id`,`receipt_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `group_payment_id_to_shop_payment_id` (
  `group_payment_id` bigint unsigned NOT NULL,
  `shop_payment_id` bigint unsigned NOT NULL,
  `keyspace_id` varbinary(128) DEFAULT NULL,
  PRIMARY KEY (`group_payment_id`,`shop_payment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `ledger` (
  `shop_id` bigint unsigned NOT NULL DEFAULT '0',
  `ledger_id` bigint unsigned NOT NULL DEFAULT '0',
  `user_id` bigint unsigned NOT NULL DEFAULT '0',
  `ledger_type` tinyint unsigned NOT NULL DEFAULT '0',
  `process_lock` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_date` int NOT NULL DEFAULT '0',
  `update_date` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`shop_id`,`ledger_id`),
  UNIQUE KEY `key_userid_ledgertype` (`user_id`,`ledger_type`),
  UNIQUE KEY `ledger_id` (`ledger_id`),
  KEY `key_update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8 COMMENT='Table used to store single ledger parent entry';

CREATE TABLE `ledger_adjustment` (
  `shop_id` bigint unsigned NOT NULL DEFAULT '0',
  `ledger_adjustment_id` bigint NOT NULL DEFAULT '0',
  `user_id` bigint NOT NULL DEFAULT '0',
  `ledger_id` bigint NOT NULL DEFAULT '0',
  `amount` int NOT NULL DEFAULT '0',
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `adjustment_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `reason_code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `staff_ldap` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `staff_dept` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `comments` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `internal_note` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`shop_id`,`ledger_adjustment_id`),
  UNIQUE KEY `ledger_adjustment_id` (`ledger_adjustment_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `staff_ldap` (`staff_ldap`(15)),
  KEY `user_id_create_date` (`user_id`,`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `ledger_amount_due` (
  `shop_id` bigint unsigned NOT NULL DEFAULT '0',
  `ledger_id` bigint unsigned NOT NULL DEFAULT '0',
  `balance` bigint NOT NULL DEFAULT '0',
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `year` smallint unsigned NOT NULL DEFAULT '0',
  `month` tinyint NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`shop_id`,`ledger_id`,`currency`,`year`,`month`),
  UNIQUE KEY `ledger_id_currency_year_month` (`ledger_id`,`currency`,`year`,`month`),
  KEY `key_update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `ledger_entries_queue` (
  `shop_id` bigint unsigned NOT NULL DEFAULT '0',
  `entry_id` bigint unsigned NOT NULL DEFAULT '0',
  `ledger_id` bigint unsigned NOT NULL DEFAULT '0',
  `origin_amount` int NOT NULL DEFAULT '0',
  `origin_currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '',
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `parent_entry_id` bigint unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  `status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `process_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `environment` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'production',
  `state_retry_count` int unsigned NOT NULL DEFAULT '0',
  `next_process_date` int unsigned NOT NULL DEFAULT '0',
  `reference_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `reference_id` bigint NOT NULL DEFAULT '0',
  `secondary_reference_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `secondary_reference_id` bigint NOT NULL DEFAULT '0',
  `is_unique` tinyint(1) DEFAULT NULL,
  `seller_credit_amount` int NOT NULL DEFAULT '0',
  `autobilling_attempted` tinyint(1) NOT NULL DEFAULT '0',
  `process_strategy` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`shop_id`,`entry_id`,`create_date`),
  UNIQUE KEY `entry_id_create_date` (`entry_id`,`create_date`),
  UNIQUE KEY `ledger_id_references_parent_entry_id_is_unique` (`ledger_id`,`reference_type`,`reference_id`,`secondary_reference_type`,`secondary_reference_id`,`parent_entry_id`,`is_unique`),
  KEY `key_create_date` (`create_date`),
  KEY `key_update_date` (`update_date`),
  KEY `key_status_create_date` (`status`(32),`create_date`),
  KEY `process_status_env_update_idx` (`process_status`(50),`environment`,`update_date`),
  KEY `status_process_update_date_idx` (`status`(32),`process_status`(50),`environment`,`next_process_date`,`update_date`),
  KEY `process_status_env_create_idx` (`process_status`(50),`environment`,`create_date`),
  KEY `reference_types_ids` (`reference_type`,`reference_id`,`secondary_reference_type`,`secondary_reference_id`),
  KEY `reference_type_status_env_idx` (`reference_type`,`status`(32),`environment`),
  KEY `ledger_id_parent_entry_id` (`ledger_id`,`parent_entry_id`),
  KEY `process_status_shop_id_env_create_date` (`process_status`(50),`shop_id`,`environment`,`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `ledger_entry` (
  `shop_id` bigint unsigned NOT NULL DEFAULT '0',
  `entry_id` bigint unsigned NOT NULL DEFAULT '0',
  `sequence_number` int NOT NULL DEFAULT '0',
  `ledger_id` bigint unsigned NOT NULL DEFAULT '0',
  `amount` bigint NOT NULL DEFAULT '0',
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `conversion_rate` float NOT NULL DEFAULT '0',
  `balance` bigint NOT NULL DEFAULT '0',
  `description` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `parent_entry_id` bigint unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  `origin_currency` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT '',
  PRIMARY KEY (`shop_id`,`entry_id`),
  UNIQUE KEY `entry_id` (`entry_id`),
  KEY `key_create_date` (`create_date`),
  KEY `key_update_date` (`update_date`),
  KEY `key_ledger_id` (`ledger_id`,`sequence_number`),
  KEY `key_ledger_id_create_date_sequence_number` (`ledger_id`,`create_date`,`sequence_number`),
  KEY `key_parent_entry_id` (`parent_entry_id`),
  KEY `key_shop_id_ledger_id_sequence_number_create_date` (`shop_id`,`ledger_id`,`sequence_number`,`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8 COMMENT='Table used to store every ledger entry accrued as part of fees, payments, adjustments etc';

CREATE TABLE `ledger_entry_tax_details` (
  `shop_id` bigint unsigned NOT NULL COMMENT 'References the Etsy shop',
  `ledger_entry_tax_details_id` bigint unsigned NOT NULL COMMENT 'Ledger entry tax details ID',
  `ledger_entry_id` bigint unsigned NOT NULL COMMENT 'References the ledger entry this tax detail belongs to',
  `tax_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'The tax result code (e.g. TAXABLE, NONTAXABLE)',
  `imposition` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'The imposition (e.g. GST/HST/QST/PST)',
  `jurisdiction` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'The jurisdiction (e.g. CANADA, or the province CA_BC)',
  `calculated_tax` int DEFAULT NULL COMMENT 'The tax for this imposition type in the currencies base amount',
  `effective_rate` float DEFAULT NULL COMMENT 'The tax rate for this imposition type in percentage',
  `tax_id_types` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'The tax id types the seller has that apply to this imposition type',
  `currency` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The currency of this tax',
  `create_date` int unsigned NOT NULL COMMENT 'Created date',
  `update_date` int unsigned NOT NULL COMMENT 'Updated date',
  PRIMARY KEY (`shop_id`,`ledger_entry_tax_details_id`),
  UNIQUE KEY `ledger_entry_tax_details_id` (`ledger_entry_tax_details_id`),
  KEY `ledger_entry_id` (`ledger_entry_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `ledger_mapping` (
  `shop_id` bigint unsigned NOT NULL DEFAULT '0',
  `ledger_entry_id` bigint unsigned NOT NULL DEFAULT '0',
  `reference_type` tinyint unsigned NOT NULL DEFAULT '0',
  `reference_id` bigint unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  `origin_reference_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `origin_reference_id` bigint unsigned DEFAULT '0',
  `ledger_id` bigint unsigned NOT NULL DEFAULT '0',
  `secondary_reference_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `secondary_reference_id` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`shop_id`,`ledger_entry_id`),
  UNIQUE KEY `ledger_entry_id` (`ledger_entry_id`),
  KEY `key_update_date` (`update_date`),
  KEY `key_reference_id_type` (`reference_id`,`reference_type`),
  KEY `key_origin_reference_id` (`origin_reference_id`),
  KEY `key_origin_ref_type_date_ledger` (`origin_reference_type`(50),`create_date`,`ledger_id`),
  KEY `key_shop_ledger_origin_ref_id_origin_ref_type_create_date` (`shop_id`,`ledger_id`,`origin_reference_id`,`origin_reference_type`(50),`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8 COMMENT='Table used to store mapping between ledger entries as what they refer to. Eg: Order IDs etc.';

CREATE TABLE `ledger_rollup` (
  `shop_id` bigint unsigned NOT NULL DEFAULT '0',
  `rollup_id` bigint unsigned NOT NULL DEFAULT '0',
  `ledger_id` bigint unsigned NOT NULL DEFAULT '0',
  `parent_category` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `category` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `period` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `period_start_date` int unsigned NOT NULL DEFAULT '0',
  `period_end_date` int unsigned NOT NULL DEFAULT '0',
  `amount` bigint NOT NULL DEFAULT '0',
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `rollup_style` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'net_balance',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`shop_id`,`rollup_id`),
  UNIQUE KEY `rollup_id` (`rollup_id`),
  KEY `key_update` (`ledger_id`,`parent_category`,`category`,`currency`,`period_start_date`,`period_end_date`),
  KEY `key_ledger_id_period` (`ledger_id`,`period`,`period_start_date`),
  KEY `key_update_date` (`update_date`),
  KEY `key_create_date` (`create_date`),
  KEY `key_update_style` (`ledger_id`,`rollup_style`,`parent_category`,`category`,`currency`,`period_start_date`,`period_end_date`),
  KEY `key_ledger_id_style_period` (`ledger_id`,`rollup_style`,`period`,`period_start_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8 COMMENT='Table used to store rollups of ledger entries per ledger';

CREATE TABLE `payment_id_to_donation_payment_id` (
  `payment_id` bigint unsigned NOT NULL,
  `donation_payment_id` varbinary(128) DEFAULT NULL,
  PRIMARY KEY (`payment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `payment_id_to_payment_adjustment_id` (
  `payment_id` bigint unsigned NOT NULL,
  `payment_adjustment_id` bigint unsigned NOT NULL,
  `keyspace_id` varbinary(128) DEFAULT NULL,
  PRIMARY KEY (`payment_id`,`payment_adjustment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `payments` (
  `payment_id` bigint unsigned NOT NULL,
  `buyer_user_id` bigint unsigned NOT NULL,
  `shop_id` bigint unsigned NOT NULL,
  `receipt_id` bigint unsigned DEFAULT NULL,
  `purchase_order_id` bigint unsigned DEFAULT NULL,
  `amount_gross` int NOT NULL,
  `amount_fees` int NOT NULL,
  `marketplace_fee_amount` int NOT NULL DEFAULT '0',
  `amount_vat` int unsigned NOT NULL DEFAULT '0',
  `amount_buyer_fee` int unsigned NOT NULL DEFAULT '0',
  `amount_net` int NOT NULL,
  `posted_gross` int DEFAULT NULL,
  `posted_fees` int DEFAULT NULL,
  `posted_vat` int unsigned NOT NULL DEFAULT '0',
  `posted_buyer_fee` int unsigned NOT NULL DEFAULT '0',
  `posted_net` int DEFAULT NULL,
  `posted_date` int unsigned DEFAULT NULL,
  `adjusted_gross` int DEFAULT NULL,
  `adjusted_fees` int DEFAULT NULL,
  `adjusted_vat` int unsigned DEFAULT NULL,
  `adjusted_buyer_fee` int unsigned DEFAULT NULL,
  `adjusted_net` int DEFAULT NULL,
  `currency` varchar(3) NOT NULL,
  `currency_fxrate` bigint unsigned DEFAULT NULL,
  `ledger_market_fxrate` bigint unsigned DEFAULT NULL,
  `ledger_markdown_rate` int unsigned DEFAULT NULL,
  `ledger_markdown_amount` int DEFAULT NULL,
  `shop_amount` int DEFAULT NULL,
  `shop_currency` varchar(3) DEFAULT NULL,
  `buyer_amount` int DEFAULT NULL,
  `buyer_amount_etsy_coupon` int NOT NULL DEFAULT '0',
  `buyer_currency` varchar(3) DEFAULT NULL,
  `buyer_currency_fxrate` bigint unsigned DEFAULT NULL,
  `ledger_to_usd_fxrate` bigint unsigned DEFAULT NULL,
  `ledger_to_eur_fxrate` bigint unsigned DEFAULT NULL,
  `buyer_to_usd_fxrate` bigint unsigned DEFAULT NULL,
  `buyer_to_eur_fxrate` bigint unsigned DEFAULT NULL,
  `shipping_address_id` bigint unsigned NOT NULL,
  `shipping_user_id` bigint unsigned DEFAULT NULL,
  `billing_address_id` bigint unsigned NOT NULL DEFAULT '0',
  `apply_gift_card_balance` tinyint(1) DEFAULT NULL,
  `payment_method` varchar(255) NOT NULL DEFAULT 'cc',
  `status` varchar(20) NOT NULL,
  `process_status` varchar(20) NOT NULL,
  `processing_fee_rate` int unsigned DEFAULT NULL,
  `processing_fee_fixed` int unsigned DEFAULT NULL,
  `vat_rate` int unsigned NOT NULL DEFAULT '0',
  `vat_fee_amount` int unsigned NOT NULL DEFAULT '0',
  `vat_fee_rate` int unsigned NOT NULL DEFAULT '0',
  `shipped_date` int unsigned DEFAULT NULL,
  `earliest_disburse_date` int NOT NULL,
  `sent_pending_email_date` int unsigned DEFAULT NULL,
  `last_failure_date` int unsigned DEFAULT NULL,
  `state_retry_count` int unsigned DEFAULT '0',
  `completed_processing_date` int unsigned DEFAULT NULL,
  `iovation_blackbox` text,
  `ip_address` text,
  `network_latency` int unsigned DEFAULT NULL,
  `is_guest` tinyint unsigned NOT NULL DEFAULT '0',
  `environment` varchar(50) DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `receipt_group_id` bigint unsigned DEFAULT NULL,
  `amount_tax` int unsigned NOT NULL DEFAULT '0',
  `posted_tax` int unsigned NOT NULL DEFAULT '0',
  `adjusted_tax` int unsigned DEFAULT NULL,
  `next_process_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`payment_id`),
  KEY `buyer_user_id` (`buyer_user_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `shop_id` (`shop_id`,`status`,`shipped_date`),
  KEY `environment` (`environment`,`create_date`),
  KEY `completed_processing_date` (`completed_processing_date`),
  KEY `shop_id_create_date` (`shop_id`,`create_date`),
  KEY `shop_id_status_posted_date` (`shop_id`,`status`,`posted_date`),
  KEY `buyer_currency` (`buyer_currency`,`create_date`),
  KEY `currency` (`currency`,`create_date`),
  KEY `process_status` (`process_status`,`environment`,`update_date`),
  KEY `shop_id_earliest_posted` (`shop_id`,`earliest_disburse_date`,`posted_date`),
  KEY `receipt_id` (`receipt_id`,`create_date`),
  KEY `purchase_order_id` (`purchase_order_id`,`create_date`),
  KEY `payment_method` (`payment_method`,`create_date`),
  KEY `shop_id_2` (`shop_id`,`status`,`create_date`),
  KEY `count_group_payments_processing_statuses_idx` (`shop_id`,`receipt_id`,`purchase_order_id`,`status`,`process_status`),
  KEY `count_multi_shop_payments_processing_statuses_idx` (`receipt_group_id`,`status`,`process_status`),
  KEY `status_process_update_date` (`status`,`process_status`,`environment`,`next_process_date`,`update_date`),
  KEY `status_sent_pending_email_date` (`status`,`sent_pending_email_date`,`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `payments_actions` (
  `payment_action_id` bigint unsigned NOT NULL,
  `payment_id` bigint unsigned NOT NULL,
  `action` varchar(100) NOT NULL,
  `action_start_date` int unsigned NOT NULL,
  `action_complete_date` int unsigned DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned DEFAULT NULL,
  PRIMARY KEY (`payment_action_id`),
  KEY `payment_id` (`payment_id`),
  KEY `action_start_date` (`action_start_date`),
  KEY `action_complete_date` (`action_complete_date`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `payments_adjustments` (
  `payment_adjustment_id` bigint unsigned NOT NULL,
  `payment_id` bigint unsigned NOT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `process_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_admin` tinyint(1) NOT NULL,
  `is_etsy_credit` tinyint(1) NOT NULL DEFAULT '0',
  `is_bulk_refund` tinyint(1) NOT NULL DEFAULT '0',
  `user_id` bigint unsigned NOT NULL COMMENT 'the user issuing the adjustment',
  `reason_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `total_adjustment_amount` int DEFAULT NULL,
  `shop_total_adjustment_amount` int DEFAULT NULL,
  `buyer_total_adjustment_amount` int DEFAULT NULL,
  `total_fee_adjustment_amount` int DEFAULT NULL,
  `total_vat_adjustment_amount` int DEFAULT NULL,
  `total_loyalty_shipping_adjustment_amount` int DEFAULT NULL,
  `concession_account_id` bigint unsigned DEFAULT NULL,
  `vat_credit_note_id` bigint unsigned NOT NULL DEFAULT '0',
  `current_fx_rate` bigint unsigned NOT NULL DEFAULT '10000000',
  `applied_fx_rate` bigint unsigned NOT NULL DEFAULT '10000000',
  `next_process_date` int unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `reason_text` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `serialized_data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `state_retry_count` int unsigned NOT NULL DEFAULT '0',
  `environment` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `total_tax_adjustment_amount` int DEFAULT NULL,
  `total_buyer_fee_adjustment_amount` int DEFAULT NULL COMMENT 'Total Buyer Fee Adjustment Amount in shop payment currency',
  `tax_finalization_date` int unsigned NOT NULL DEFAULT '0',
  `refund_create_source` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `total_etsy_coupon_adjustment_amount` int DEFAULT NULL,
  `refund_method_preference_token` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`payment_adjustment_id`),
  KEY `payment_id` (`payment_id`,`create_date`),
  KEY `user_id` (`user_id`,`create_date`),
  KEY `create_date` (`create_date`),
  KEY `process_status` (`process_status`,`environment`,`update_date`),
  KEY `next_process_date_composite` (`process_status`,`environment`,`next_process_date`),
  KEY `vat_credit_note_id` (`vat_credit_note_id`),
  KEY `update_date` (`update_date`),
  KEY `refund_method_preference_token` (`refund_method_preference_token`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `payments_adjustments_items` (
  `payment_adjustment_item_id` bigint unsigned NOT NULL,
  `payment_adjustment_id` bigint unsigned NOT NULL,
  `adjustment_type` varchar(10) NOT NULL,
  `amount` int NOT NULL,
  `shop_amount` int DEFAULT NULL,
  `transaction_id` bigint DEFAULT NULL,
  `bill_payment_id` bigint unsigned DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned DEFAULT NULL,
  PRIMARY KEY (`payment_adjustment_id`,`payment_adjustment_item_id`),
  UNIQUE KEY `payment_adjustment_item_id` (`payment_adjustment_item_id`),
  KEY `payment_adjustment_id` (`payment_adjustment_id`,`create_date`),
  KEY `create_date` (`create_date`),
  KEY `txn_id_adj_type_key` (`transaction_id`,`adjustment_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `payments_fees` (
  `payment_fee_id` bigint unsigned NOT NULL,
  `payment_id` bigint unsigned NOT NULL,
  `fee_type` varchar(10) NOT NULL,
  `amount` int unsigned NOT NULL,
  `adjusted_amount` int unsigned DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`payment_fee_id`),
  UNIQUE KEY `payment_id` (`payment_id`,`fee_type`),
  KEY `create_date` (`create_date`),
  KEY `update_date_idx` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `payments_fees_adjustments` (
  `payment_fee_adjustment_id` bigint unsigned NOT NULL,
  `payment_fee_id` bigint unsigned NOT NULL,
  `payment_adjustment_id` bigint unsigned NOT NULL,
  `amount` int unsigned NOT NULL,
  `create_date` int unsigned NOT NULL,
  PRIMARY KEY (`payment_adjustment_id`,`payment_fee_adjustment_id`),
  UNIQUE KEY `payment_fee_adjustment_id` (`payment_fee_adjustment_id`),
  KEY `payment_fee_id` (`payment_fee_id`,`payment_adjustment_id`,`create_date`),
  KEY `payment_fee_id_2` (`payment_fee_id`,`create_date`),
  KEY `payment_adjustment_id` (`payment_adjustment_id`,`create_date`),
  KEY `create_date` (`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `payments_spa_reserve_audit` (
  `payments_spa_reserve_audit_id` bigint unsigned NOT NULL,
  `shop_id` bigint unsigned NOT NULL,
  `exposure_source` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'FK: etsy_aux.admin_reason.mnemonic',
  `exposure_source_detail` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `exposure_percentage` int unsigned NOT NULL DEFAULT '0',
  `exposure_end_date` int unsigned NOT NULL DEFAULT '0',
  `spa_action` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'add | remove',
  `spa_action_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'failure | success',
  `spa_action_source_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'control | admin | ...',
  `spa_action_source_id` bigint unsigned NOT NULL DEFAULT '0',
  `spa_action_source_revision_id` bigint unsigned NOT NULL DEFAULT '0',
  `batch_id` bigint unsigned NOT NULL DEFAULT '0',
  `note` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT (_utf8mb4'') COMMENT 'used for additional info on success/failure',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`payments_spa_reserve_audit_id`),
  KEY `shop_id` (`shop_id`),
  KEY `spa_action_source_id` (`spa_action_source_id`),
  KEY `spa_action_source_revision_id` (`spa_action_source_revision_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `batch_id` (`batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `payoneer_accounts` (
  `payoneer_account_id` bigint unsigned NOT NULL,
  `shop_id` bigint unsigned NOT NULL,
  `payoneer_id` int unsigned DEFAULT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `registration_link` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `decline_reason` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `encrypted_access_token` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `access_token_expiration_date` bigint unsigned DEFAULT NULL,
  `encrypted_refresh_token` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `refresh_token_expiration_date` bigint unsigned DEFAULT NULL,
  `oauth_state` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `user_identity_id` bigint unsigned DEFAULT NULL,
  `bank_account_id` bigint unsigned DEFAULT NULL,
  `iso_country_code` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `already_have_an_account` tinyint(1) NOT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`payoneer_account_id`),
  KEY `shop_id_idx` (`shop_id`),
  KEY `payoneer_id_idx` (`payoneer_id`),
  KEY `access_token_expiration_date_idx` (`access_token_expiration_date`),
  KEY `create_date_idx` (`create_date`),
  KEY `update_date_idx` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `payoneer_disbursement_job_id_to_shop_id` (
  `disbursement_job_id` bigint unsigned NOT NULL,
  `shop_id` bigint unsigned NOT NULL,
  `keyspace_id` varbinary(128) DEFAULT NULL,
  PRIMARY KEY (`disbursement_job_id`,`shop_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `payoneer_items` (
  `payoneer_item_id` bigint unsigned NOT NULL,
  `disbursement_job_id` bigint unsigned NOT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `process_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `disbursement_id` bigint unsigned NOT NULL,
  `amount` bigint unsigned NOT NULL,
  `currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ledger_amount` bigint unsigned NOT NULL DEFAULT '0',
  `ledger_currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `iso_country_code` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `conversion_rate` float NOT NULL DEFAULT '0',
  `bank_account_id` bigint unsigned NOT NULL,
  `shop_id` bigint unsigned NOT NULL,
  `retry_count` int unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`payoneer_item_id`),
  KEY `job_id_idx` (`disbursement_job_id`),
  KEY `bank_account_id_idx` (`bank_account_id`),
  KEY `disbursement_id_idx` (`disbursement_id`),
  KEY `update_date_idx` (`update_date`),
  KEY `create_date_idx` (`create_date`),
  KEY `process_status_idx` (`process_status`),
  KEY `iso_country_code_idx` (`iso_country_code`),
  KEY `shop_id_idx` (`shop_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `paypal_txns` (
  `paypal_txn_id` bigint unsigned NOT NULL,
  `txn_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `reference_id` bigint unsigned NOT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `pending_reason` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `seller_paypal_account_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `auth_transaction_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `token` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `original_ref_id` bigint unsigned DEFAULT NULL,
  `amount` int NOT NULL,
  `currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `auth_raw_request` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `auth_raw_response` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `paypal_order_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '',
  `paypal_api_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '',
  `paypal_payee_email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `iso_country_code` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payin_entity` varchar(48) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `settlement_entity` varchar(48) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`reference_id`,`paypal_txn_id`),
  UNIQUE KEY `paypal_txn_id` (`paypal_txn_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `reference_id` (`reference_id`,`txn_type`,`create_date`),
  KEY `status` (`status`,`create_date`),
  KEY `token` (`token`),
  KEY `paypal_order_id` (`paypal_order_id`),
  KEY `auth_transaction_id` (`auth_transaction_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `plaid_bank_transfer_events` (
  `plaid_bank_transfer_event_id` bigint unsigned NOT NULL COMMENT 'Etsy: Table primary key.',
  `shop_id` bigint unsigned NOT NULL COMMENT 'Etsy: Shop ID and shard key.',
  `plaid_session_id` bigint unsigned NOT NULL COMMENT 'Etsy: Plaid Session ID.',
  `plaid_event_id` bigint unsigned NOT NULL COMMENT 'Plaid: Unique identifier for this event. IDs are sequential unsigned 64-bit integers.',
  `plaid_account_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Plaid: The account ID associated with the bank transfer.',
  `processing_state` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'created' COMMENT 'Records the processing state for the record. Could be one of: `stored`, `processed`.',
  `plaid_bank_transfer_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Plaid: Unique identifier for a bank transfer.',
  `plaid_bank_transfer_amount` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Plaid: The bank transfer amount.',
  `plaid_bank_transfer_iso_currency_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Plaid: The currency of the bank transfer amount.',
  `plaid_bank_transfer_type` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Plaid: The type of transfer. Possible values: debit, credit.',
  `plaid_direction` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Plaid: Indicates the direction of the transfer. Possible values: outbound, inbound, null.',
  `plaid_event_type` varchar(27) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Plaid: The type of event that this bank transfer represents. Possible values: pending, cancelled, failed, posted, reversed.',
  `plaid_failure_reason` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Plaid: The failure reason if the type of this transfer is "failed" or "reversed". Null value otherwise.',
  `plaid_failure_ach_return_code` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Plaid: The ACH return code, e.g. R01.',
  `plaid_failure_description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Plaid: A human-readable description of the reason for the failure or reversal.',
  `plaid_origination_account_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Plaid: The ID of the origination account that this balance belongs to.',
  `plaid_timestamp` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Plaid: The datetime when this event occurred. This will be of the form 2006-01-02T15:04:05Z.',
  `plaid_request_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Plaid: A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.',
  `create_date` int unsigned NOT NULL COMMENT 'Etsy: Record create date',
  `update_date` int unsigned NOT NULL COMMENT 'Etsy: Record update date',
  PRIMARY KEY (`plaid_bank_transfer_event_id`),
  UNIQUE KEY `plaid_event_id` (`plaid_event_id`),
  KEY `shop_id` (`shop_id`),
  KEY `shop_plaid_session` (`plaid_session_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `processor_txn_reference` (
  `processor_txn_reference_id` bigint unsigned NOT NULL,
  `reference_id` bigint unsigned NOT NULL COMMENT 'CC txn id',
  `reference_txn_type_id` int unsigned NOT NULL COMMENT 'Payment, refund, etc. txn type id',
  `processor_txn_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Processor txn id received from processor',
  `processor` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `success` tinyint(1) NOT NULL DEFAULT '1',
  `processor_data` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'JSON data from the processor',
  `create_date` bigint unsigned NOT NULL,
  `update_date` bigint unsigned NOT NULL,
  PRIMARY KEY (`processor_txn_reference_id`),
  KEY `reference_id_idx` (`reference_id`),
  KEY `txn_type_id_idx` (`reference_txn_type_id`,`reference_id`,`url`,`success`),
  KEY `processor_txn_id_idx` (`processor_txn_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `razorpay_kyc_errors` (
  `razorpay_kyc_error_id` bigint unsigned NOT NULL,
  `razorpay_kyc_record_id` bigint unsigned NOT NULL COMMENT 'maps to record in razorpay_kyc_records',
  `shop_id` bigint unsigned NOT NULL,
  `kyc_record_status_during_error` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'status of kyc record at the time of error',
  `error_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'UNKNOWN' COMMENT 'type of error (ex. ERROR, REQUIREMENT, UNKNOWN, etc)',
  `razorpay_error_response` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'full error response from Razorpay',
  `razorpay_field_reference` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'field_reference from razorpay_error_response',
  `razorpay_reason_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'reason_code from razorpay_error_response',
  `razorpay_description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'description from Razorpay',
  `resolve_date` int unsigned DEFAULT NULL COMMENT 'date when this error was resolved for this kyc attempt',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`razorpay_kyc_error_id`),
  KEY `update_date` (`update_date`),
  KEY `create_date` (`create_date`),
  KEY `resolve_date` (`resolve_date`),
  KEY `razorpay_kyc_record_id_and_error_type_idx` (`razorpay_kyc_record_id`,`error_type`,`resolve_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `razorpay_kyc_records` (
  `razorpay_kyc_record_id` bigint unsigned NOT NULL,
  `shop_id` bigint unsigned NOT NULL,
  `status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `process_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `business_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'one of Razorpays business types',
  `bank_account_id` bigint unsigned DEFAULT NULL,
  `pan_token_id` bigint unsigned DEFAULT NULL,
  `user_identity_id` bigint unsigned DEFAULT NULL,
  `linked_account_id` bigint unsigned DEFAULT NULL,
  `notes` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `environment` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state_retry_count` int unsigned DEFAULT '0' COMMENT '# of retries so far at the current status',
  `next_process_date` int unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`razorpay_kyc_record_id`),
  KEY `shop_idx` (`shop_id`,`status`,`create_date`),
  KEY `process_status_update_date` (`process_status`,`environment`,`next_process_date`,`update_date`),
  KEY `update_date` (`update_date`),
  KEY `create_date` (`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `razorpay_kyc_requirements` (
  `razorpay_kyc_requirement_id` bigint unsigned NOT NULL,
  `razorpay_kyc_record_id` bigint unsigned NOT NULL COMMENT 'maps to record in razorpay_kyc_records',
  `shop_id` bigint unsigned NOT NULL,
  `razorpay_entity_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'UNKNOWN' COMMENT 'entity type (ex. LINKED_ACCOUNT, STAKEHOLDER, ROUTE)',
  `razorpay_field_reference` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'field_reference of this requirement',
  `razorpay_latest_response` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'latest full response from Razorpay for this requirement',
  `razorpay_latest_reason_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'latest reason_code from Razorpay for this requirement',
  `razorpay_latest_description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'latest description from Razorpay for this requirement',
  `seller_updated_info_date` int unsigned DEFAULT NULL COMMENT 'date when seller updated the applicable info for this requirement',
  `resolve_date` int unsigned DEFAULT NULL COMMENT 'date when Razorpay resolved this requirement',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`razorpay_kyc_requirement_id`),
  KEY `update_date` (`update_date`),
  KEY `create_date` (`create_date`),
  KEY `razorpay_kyc_record_id_and_seller_updated_info_date_idx` (`razorpay_kyc_record_id`,`shop_id`,`seller_updated_info_date`),
  KEY `razorpay_kyc_record_id_and_razorpay_entity_type_idx` (`razorpay_kyc_record_id`,`shop_id`,`razorpay_entity_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `real_time_account_updater_items` (
  `account_updater_item_id` bigint unsigned NOT NULL,
  `card_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL DEFAULT '0',
  `reference_id` bigint unsigned NOT NULL,
  `mid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `change_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `new_expiry_month` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `new_expiry_year` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `process_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`account_updater_item_id`),
  KEY `card_id` (`card_id`),
  KEY `reference_id` (`reference_id`),
  KEY `update_date` (`update_date`),
  KEY `create_date` (`create_date`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `receipt_id_to_shop_payment_id` (
  `receipt_id` bigint unsigned NOT NULL,
  `shop_payment_id` varbinary(128) DEFAULT NULL,
  PRIMARY KEY (`receipt_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `recoupments` (
  `recoupment_id` bigint unsigned NOT NULL,
  `ledger_id` bigint unsigned NOT NULL,
  `status` varchar(20) NOT NULL,
  `amount` int unsigned DEFAULT NULL,
  `currency` varchar(3) DEFAULT NULL,
  `scheduled_date` int unsigned NOT NULL COMMENT 'date this is/was scheduled for',
  `execution_date` int unsigned DEFAULT NULL COMMENT 'date this was executed',
  `method` varchar(20) NOT NULL COMMENT 'paymentech, other?',
  `ledger_entry_id` bigint unsigned DEFAULT NULL COMMENT 'seller_ledger recoupment credit entry',
  `payment_adjustment_id` bigint unsigned DEFAULT NULL COMMENT 'if this is to be settled following a refund',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `reference_id` bigint unsigned DEFAULT NULL,
  `reference_type` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`recoupment_id`),
  KEY `ledger_id` (`ledger_id`,`create_date`),
  KEY `status` (`status`,`create_date`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `payment_adjustment_id` (`payment_adjustment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `refund_credits` (
  `refund_credit_id` bigint unsigned NOT NULL,
  `payment_adjustment_id` bigint unsigned NOT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'whether the refund is active or exhausted',
  `buyer_user_id` bigint unsigned NOT NULL,
  `original_balance` int NOT NULL COMMENT 'full value of the gift card',
  `available_balance` int NOT NULL COMMENT 'set to original_balance value at creation, then deducted from as purchases are made with the credit balance',
  `currency_code` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_locked` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'boolean indicating if gift card is locked',
  `exhausted_date` int unsigned DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`refund_credit_id`),
  UNIQUE KEY `payment_adjustment_id` (`payment_adjustment_id`),
  KEY `buyer_user_id` (`buyer_user_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `refund_method_preferences` (
  `refund_method_preference_id` bigint unsigned NOT NULL,
  `buyer_user_id` bigint unsigned NOT NULL,
  `preferred_refund_method` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'either `original_payment_method` or `refund_credit`',
  `receipt_id` bigint unsigned NOT NULL,
  `payment_adjustment_id` bigint unsigned DEFAULT NULL,
  `order_help_request_id` bigint unsigned DEFAULT NULL,
  `preference_source` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'either `atlas` or `seller_initiated` or `help_with_order` or `case_system`',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`refund_method_preference_id`),
  UNIQUE KEY `payment_adjustment_id` (`payment_adjustment_id`),
  UNIQUE KEY `order_help_request_id` (`order_help_request_id`),
  KEY `payment_adjustment_buyer_idx` (`payment_adjustment_id`,`buyer_user_id`),
  KEY `receipt_buyer_idx` (`receipt_id`,`buyer_user_id`),
  KEY `buyer_user_id` (`buyer_user_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `preference_source` (`preference_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `seller_onboarding_fee` (
  `seller_onboarding_fee_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `amount` int NOT NULL DEFAULT '0',
  `amount_tax` int NOT NULL DEFAULT '0',
  `amount_fee` int NOT NULL DEFAULT '0',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `process_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `state_retry_count` int unsigned DEFAULT NULL,
  `environment` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_failure_date` int unsigned DEFAULT NULL,
  `next_process_date` int unsigned NOT NULL DEFAULT '0',
  `email_sent_date` int unsigned DEFAULT NULL,
  `settled_date` int unsigned DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`seller_onboarding_fee_id`),
  KEY `user_id` (`user_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `process_status_env_process_date` (`process_status`,`environment`,`next_process_date`,`update_date`),
  KEY `status_process_status` (`status`,`process_status`,`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `seller_onboarding_fee_adjustment` (
  `seller_onboarding_fee_adjustment_id` bigint unsigned NOT NULL,
  `seller_onboarding_fee_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `total_adjustment_amount` int NOT NULL DEFAULT '0',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `process_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `state_retry_count` int unsigned DEFAULT NULL,
  `environment` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `next_process_date` int unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`seller_onboarding_fee_adjustment_id`),
  UNIQUE KEY `seller_onboarding_fee_id` (`seller_onboarding_fee_id`),
  KEY `user_id` (`user_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `process_status_env_process_date` (`process_status`,`environment`,`next_process_date`,`update_date`),
  KEY `status_process_status` (`status`,`process_status`,`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `shop_payments` (
  `shop_payment_id` bigint unsigned NOT NULL,
  `group_payment_id` bigint unsigned DEFAULT NULL,
  `shop_id` bigint unsigned NOT NULL,
  `receipt_id` bigint unsigned DEFAULT NULL,
  `purchase_order_id` bigint unsigned DEFAULT NULL,
  `shop_amount` int DEFAULT NULL,
  `shop_currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buyer_amount_etsy_coupon` int NOT NULL DEFAULT '0',
  `buyer_amount_buyer_fee` int unsigned NOT NULL DEFAULT '0',
  `buyer_amount` int NOT NULL DEFAULT '0',
  `amount_gross` int NOT NULL,
  `amount_fees` int NOT NULL,
  `amount_vat` int unsigned NOT NULL DEFAULT '0',
  `amount_net` int NOT NULL,
  `posted_gross` int DEFAULT NULL,
  `posted_fees` int DEFAULT NULL,
  `posted_vat` int unsigned NOT NULL DEFAULT '0',
  `posted_net` int DEFAULT NULL,
  `posted_date` int unsigned DEFAULT NULL,
  `adjusted_gross` int DEFAULT NULL,
  `adjusted_fees` int DEFAULT NULL,
  `adjusted_vat` int unsigned DEFAULT NULL,
  `adjusted_net` int DEFAULT NULL,
  `currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `currency_fxrate` bigint unsigned DEFAULT NULL,
  `ledger_market_fxrate` bigint unsigned DEFAULT NULL,
  `ledger_markdown_rate` int unsigned DEFAULT NULL,
  `ledger_markdown_amount` int DEFAULT NULL,
  `markdown_delta` bigint DEFAULT NULL,
  `markup_delta` bigint DEFAULT NULL,
  `adjusted_markup_delta` bigint DEFAULT NULL,
  `adjusted_markdown_delta` bigint DEFAULT NULL,
  `ledger_to_usd_fxrate` bigint unsigned DEFAULT NULL,
  `ledger_to_eur_fxrate` bigint unsigned DEFAULT NULL,
  `buyer_currency_fxrate` bigint unsigned DEFAULT NULL,
  `processing_fee_rate` int unsigned DEFAULT NULL,
  `processing_fee_fixed` int unsigned DEFAULT NULL,
  `vat_rate` int unsigned NOT NULL DEFAULT '0',
  `shipped_date` int unsigned DEFAULT NULL,
  `earliest_disburse_date` int NOT NULL,
  `sent_pending_email_date` int unsigned DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `process_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `amount_tax` int unsigned NOT NULL DEFAULT '0',
  `posted_tax` int unsigned NOT NULL DEFAULT '0',
  `adjusted_tax` int unsigned DEFAULT NULL,
  `amount_buyer_fee` int unsigned NOT NULL DEFAULT '0',
  `posted_buyer_fee` int unsigned NOT NULL DEFAULT '0',
  `adjusted_buyer_fee` int unsigned DEFAULT NULL,
  `exposure_percentage` int unsigned NOT NULL DEFAULT '0',
  `exposure_end_date` int unsigned NOT NULL DEFAULT '0',
  `amount_etsy_coupon` int NOT NULL DEFAULT '0',
  `posted_etsy_coupon` int NOT NULL DEFAULT '0',
  `adjusted_etsy_coupon` int DEFAULT NULL,
  `amount_loyalty_shipping_discount` int NOT NULL DEFAULT '0',
  `posted_loyalty_shipping_discount` int NOT NULL DEFAULT '0',
  `adjusted_loyalty_shipping_discount` int DEFAULT NULL,
  `buyer_revenue_entity` varchar(48) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `seller_revenue_entity` varchar(48) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `seller_payout_entity` varchar(48) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`shop_payment_id`),
  KEY `currency` (`currency`,`create_date`),
  KEY `shop_id_earliest_posted` (`shop_id`,`earliest_disburse_date`,`posted_date`),
  KEY `receipt_id` (`receipt_id`,`create_date`),
  KEY `purchase_order_id` (`purchase_order_id`,`create_date`),
  KEY `group_payment_idx` (`group_payment_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `shop_id_create_date` (`shop_id`,`create_date`,`earliest_disburse_date`,`exposure_end_date`,`exposure_percentage`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `status_log_ytd` (
  `status_log_id` bigint unsigned NOT NULL,
  `reference_id` bigint unsigned NOT NULL,
  `reference_type` varchar(50) NOT NULL,
  `status` varchar(30) NOT NULL,
  `process_status` varchar(30) DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `create_date_micros` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`status_log_id`,`create_date`),
  KEY `reference_id` (`reference_id`,`reference_type`,`create_date`),
  KEY `reference_type` (`reference_type`,`create_date`),
  KEY `create_date` (`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `subscription_invoices` (
  `subscription_invoice_id` bigint unsigned NOT NULL,
  `subscription_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `plan_id` bigint unsigned NOT NULL,
  `card_id` bigint unsigned NOT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `period_start` int unsigned NOT NULL,
  `period_end` int unsigned NOT NULL,
  `amount` int NOT NULL,
  `amount_tax` int NOT NULL DEFAULT '0',
  `currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_first_in_series` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'boolean - is this the initial invoice in a new subscription',
  `tax_client` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`user_id`,`subscription_invoice_id`),
  KEY `subscription` (`subscription_id`),
  KEY `status` (`status`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `subscription_payment_adjustments` (
  `subscription_payment_adjustment_id` bigint unsigned NOT NULL,
  `subscription_payment_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `total_adjustment_amount` int NOT NULL DEFAULT '0',
  `total_tax_adjustment_amount` int NOT NULL DEFAULT '0',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `process_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_failure_date` int unsigned DEFAULT NULL,
  `next_process_date` int unsigned DEFAULT NULL,
  `state_retry_count` int unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `environment` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`user_id`,`subscription_payment_adjustment_id`),
  UNIQUE KEY `subscription_payment_id` (`subscription_payment_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `process_status_env_process_date` (`process_status`(16),`environment`(16),`next_process_date`,`update_date`),
  KEY `status_process_status` (`status`(16),`process_status`(16),`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `subscription_payments` (
  `subscription_payment_id` bigint unsigned NOT NULL,
  `subscription_invoice_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `amount` int NOT NULL,
  `amount_tax` int NOT NULL DEFAULT '0',
  `currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `process_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_failure_date` int unsigned DEFAULT NULL,
  `next_process_date` int unsigned DEFAULT NULL,
  `state_retry_count` int unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `environment` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`user_id`,`subscription_payment_id`),
  KEY `subscription_invoice` (`subscription_invoice_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `process_status_env_process_date` (`process_status`,`environment`,`next_process_date`,`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `subscriptions` (
  `subscription_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `plan_id` bigint unsigned NOT NULL,
  `plan_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `card_id` bigint unsigned NOT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `current_period_start` int unsigned NOT NULL,
  `current_period_end` int unsigned NOT NULL,
  `cancel_at_period_end` tinyint(1) NOT NULL DEFAULT '0',
  `start_date` int unsigned NOT NULL,
  `cancelled_date` int unsigned DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`user_id`,`subscription_id`),
  KEY `status` (`status`),
  KEY `plan_type` (`plan_type`),
  KEY `effective_date` (`current_period_start`,`current_period_end`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `tds_gift_cards` (
  `tds_gift_card_id` bigint unsigned NOT NULL,
  `tds_reference_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'non-redeemable unique identifier returned from TDS',
  `tds_purchase_attempt_id` bigint unsigned DEFAULT NULL COMMENT 'foreign key to tds_purchase_attempts, which is populated for 1P purchases',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'gift card status returned from TDS',
  `redeem_user_id` bigint unsigned NOT NULL,
  `original_balance` int NOT NULL COMMENT 'full value of the gift card',
  `available_balance` int NOT NULL COMMENT 'set to original_balance value at creation, then deducted from as purchases are made with the gift card balance',
  `currency_code` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_locked` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'boolean indicating if gift card is locked',
  `card_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'indicates if gift card is physical or digital',
  `purchase_date` int unsigned DEFAULT NULL COMMENT 'date when the gift card was purchased',
  `redeem_date` int unsigned DEFAULT NULL COMMENT 'date when the gift card was redeemed',
  `exhausted_date` int unsigned DEFAULT NULL COMMENT 'date when the gift card balance is fully spent',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`tds_gift_card_id`),
  UNIQUE KEY `tds_reference_id` (`tds_reference_id`),
  KEY `redeem_user_id` (`redeem_user_id`),
  KEY `redeem_date` (`redeem_date`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `tds_merchants` (
  `tds_merchant_id` bigint unsigned NOT NULL,
  `tds_gift_card_id` bigint unsigned NOT NULL,
  `merchant_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `merchant_location` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `merchant_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `merchant_city` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `merchant_state` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `merchant_zip` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `merchant_country` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `merchant_terminal_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `merchant_store_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`tds_merchant_id`),
  UNIQUE KEY `tds_gift_card_id__idx` (`tds_gift_card_id`),
  KEY `create_date__idx` (`create_date`),
  KEY `update_date__idx` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `tds_purchase_attempts` (
  `tds_purchase_attempt_id` bigint unsigned NOT NULL,
  `purchaser_identifier` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'for signed-in purchasers, this is the user_id, and for logged out purchasers, this is the guest uaid',
  `purchaser_identifier_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'either user_id or guest_uaid',
  `iso_country_code` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `currency_code` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `platform` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `preemptive_design_choice` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'the friendly name of the design the user clicked on the landing page',
  `preemptive_design_choice_id` int DEFAULT NULL COMMENT 'the id of the design the user clicked on the landing page',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`tds_purchase_attempt_id`),
  KEY `purchaser_key` (`purchaser_identifier`(16),`purchaser_identifier_type`(8)),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `threeds_authentication_preference` (
  `threeds_authentication_preference_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `reference_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `reference_id` bigint unsigned NOT NULL,
  `challenge_preference` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `reason` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `reason_reference_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `reason_reference_id` bigint unsigned DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`threeds_authentication_preference_id`),
  UNIQUE KEY `reference_type_reference_id` (`reference_type`,`reference_id`),
  KEY `user_id_reference_id` (`user_id`,`reference_id`),
  KEY `update_date` (`update_date`),
  KEY `create_date` (`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `transaction_routing_audits` (
  `transaction_routing_audit_id` bigint unsigned NOT NULL COMMENT 'pk',
  `user_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Maps to User. Used for Sharding.',
  `txn_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Type of audit, CCTXN, PPalTxn etc.',
  `txn_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Primary key for type of txn',
  `txn_metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Collection of txn data at time of audit: currency, bin_data, issuing country, buyer and seller locations',
  `audit_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'AccountingEntitySet, PaymentGatewaySelect, etc.',
  `audit_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'json blob of Audit data',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  `create_date_micros` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`transaction_routing_audit_id`),
  KEY `user_id` (`user_id`,`create_date`),
  KEY `txn_type` (`txn_type`,`txn_id`,`create_date`),
  KEY `txn_id` (`txn_id`,`create_date`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8 COMMENT='Audit Trails covering Routing Decisions for Transactions';

CREATE TABLE `vitess_etet` (
  `id` bigint unsigned NOT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `f_varchar` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `wpap_txns` (
  `wpap_txn_id` bigint unsigned NOT NULL,
  `txn_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `reference_id` bigint unsigned NOT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `epacs_reference` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `original_ref_id` bigint unsigned DEFAULT NULL,
  `amount` int NOT NULL,
  `currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `country_code` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bank_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `posting_date` int unsigned DEFAULT NULL,
  `raw_request` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `raw_response` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `payin_entity` varchar(48) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `settlement_entity` varchar(48) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`reference_id`,`wpap_txn_id`),
  UNIQUE KEY `wpap_txn_id` (`wpap_txn_id`),
  UNIQUE KEY `epacs_reference` (`epacs_reference`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `reference_id` (`reference_id`,`txn_type`,`create_date`),
  KEY `status` (`status`,`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `youlend_prequalifications` (
  `youlend_prequal_id` bigint unsigned NOT NULL,
  `shop_id` bigint unsigned NOT NULL,
  `lead_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `prequal_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `prequal_date` bigint unsigned DEFAULT NULL,
  `prequal_amount` int unsigned DEFAULT NULL,
  `currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `has_clicked_link` tinyint(1) DEFAULT '0',
  `create_date` bigint unsigned NOT NULL,
  `update_date` bigint unsigned NOT NULL,
  `process_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `next_process_date` bigint unsigned NOT NULL,
  `state_retry_count` int unsigned NOT NULL,
  `environment` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`youlend_prequal_id`),
  KEY `shop_id_idx` (`shop_id`),
  KEY `lead_id_idx` (`lead_id`(16)),
  KEY `create_date_idx` (`create_date`),
  KEY `update_date_idx` (`update_date`),
  KEY `process_status_env_process_date` (`process_status`,`environment`,`next_process_date`,`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

