CREATE DATABASE etsy_mail_0_A;
USE etsy_mail_0_A;

CREATE TABLE `cdc_etet` (
  `id` bigint unsigned NOT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `f_varchar` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `dynamic_targeting_rule_data` (
  `dynamic_targeting_rule_data_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_schedule_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_template_id` bigint unsigned NOT NULL DEFAULT '0',
  `utm_campaign` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `rule_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `dt_module_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `module_index` int unsigned NOT NULL DEFAULT '0',
  `rule_index` int unsigned NOT NULL DEFAULT '0',
  `clause_index` int unsigned NOT NULL DEFAULT '0',
  `attribute_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `attribute_condition` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `value` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `clause_condition` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`dynamic_targeting_rule_data_id`),
  KEY `create_date` (`create_date`),
  KEY `update_date` (`update_date`),
  KEY `email_campaign_schedule_id` (`email_campaign_schedule_id`,`email_campaign_template_id`),
  KEY `utm_campaign` (`utm_campaign`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_address_audience_experiments` (
  `experiment_flag` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `email_address_id` bigint unsigned NOT NULL DEFAULT '0',
  `variant` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`experiment_flag`(185),`email_address_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_address_audience_import` (
  `email_address_audience_import_id` bigint unsigned NOT NULL,
  `email_campaign_audience_id` bigint unsigned NOT NULL,
  `import_date` int NOT NULL,
  `audience_size` int NOT NULL,
  `added_recipients` int unsigned NOT NULL DEFAULT '0',
  `lost_recipients` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`email_address_audience_import_id`),
  KEY `audience_date` (`email_campaign_audience_id`,`import_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPACT;

CREATE TABLE `email_address_campaign` (
  `email_address_campaign_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_address_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_schedule_id` bigint unsigned NOT NULL DEFAULT '0',
  `last_sent_email_campaign_schedule_id` bigint unsigned NOT NULL DEFAULT '0',
  `next_schedule_order` int NOT NULL DEFAULT '0',
  `locked_by_process` varchar(255) NOT NULL DEFAULT '',
  `state` tinyint NOT NULL DEFAULT '0',
  `subscribe_date` int unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`email_address_campaign_id`),
  UNIQUE KEY `email_address_id_2` (`email_address_id`,`email_campaign_id`),
  KEY `next_schedule_idx` (`email_campaign_id`,`state`,`next_schedule_order`,`last_sent_email_campaign_schedule_id`),
  KEY `update_date` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_address_campaign_contact_list` (
  `email_address_campaign_contact_list_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_id` bigint unsigned NOT NULL DEFAULT '0',
  `name` text NOT NULL,
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`email_address_campaign_contact_list_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_address_campaign_unverified` (
  `email_address_campaign_unverified_id` bigint unsigned NOT NULL DEFAULT '0',
  `email` varchar(256) NOT NULL,
  `email_campaign_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_address_campaign_contact_list_id` bigint unsigned NOT NULL DEFAULT '0',
  `last_sent_email_campaign_schedule_id` bigint unsigned NOT NULL DEFAULT '0',
  `state` tinyint NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`email_address_campaign_unverified_id`),
  KEY `email_address_campaign_contact_list_id` (`email_address_campaign_contact_list_id`),
  KEY `email` (`email`(255)),
  KEY `distinct_user_idx` (`email_address_campaign_unverified_id`,`email_campaign_id`),
  KEY `next_schedule_idx` (`email_campaign_id`,`email_address_campaign_contact_list_id`,`state`,`last_sent_email_campaign_schedule_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_address_campaign_unverified_metadata` (
  `email_address_campaign_unverified_metadata_id` bigint unsigned NOT NULL DEFAULT '0',
  `email` varchar(256) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `type` varchar(32) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `data` varchar(256) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`email_address_campaign_unverified_metadata_id`),
  KEY `email` (`email`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8_unicode_ci ROW_FORMAT=COMPACT;

CREATE TABLE `email_campaign` (
  `email_campaign_id` bigint unsigned NOT NULL DEFAULT '0',
  `type` varchar(32) NOT NULL DEFAULT '',
  `sending_mechanism` smallint NOT NULL DEFAULT '0',
  `status` varchar(16) NOT NULL DEFAULT '',
  `name` varchar(120) NOT NULL COMMENT 'used by many queries to specify which campaign to operate on',
  `short_name` varchar(64) DEFAULT NULL COMMENT 'reserved for shortened display name in email header',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  `length` int NOT NULL DEFAULT '0',
  `frequency` int NOT NULL DEFAULT '0',
  `utm_source` varchar(64) NOT NULL DEFAULT '',
  `is_subscribed_on_signup` tinyint(1) NOT NULL DEFAULT '0',
  `is_subscribed_on_new_shop` tinyint(1) NOT NULL DEFAULT '0',
  `flow` varchar(16) NOT NULL DEFAULT '',
  `sender_name` varchar(64) NOT NULL DEFAULT '',
  `from_address` varchar(256) DEFAULT NULL,
  `reply_to_address` varchar(256) NOT NULL DEFAULT '',
  `parent_id` bigint NOT NULL DEFAULT '0',
  `currency_code` varchar(3) NOT NULL DEFAULT 'USD',
  `campaign_label` varchar(64) NOT NULL DEFAULT '' COMMENT 'used for aggregrating stats',
  `canvas_footer_path` varchar(250) NOT NULL DEFAULT '',
  PRIMARY KEY (`email_campaign_id`),
  UNIQUE KEY `email_campaign_name_idx` (`name`),
  KEY `is_subscribed_on_new_shop_idx` (`is_subscribed_on_new_shop`,`status`),
  KEY `is_subscribed_on_signup_idx` (`is_subscribed_on_signup`,`status`),
  KEY `update_date` (`update_date`),
  KEY `campaign_label_status_idx` (`campaign_label`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_campaign_adhoc_recipients` (
  `email_campaign_adhoc_recipients_id` bigint NOT NULL DEFAULT '0',
  `email_campaign_id` bigint NOT NULL DEFAULT '0',
  `email_campaign_schedule_id` bigint NOT NULL DEFAULT '0',
  `email_address_campaign_id` bigint NOT NULL DEFAULT '0',
  `locked_by_process` varchar(255) NOT NULL DEFAULT '',
  `dispatched` tinyint(1) NOT NULL DEFAULT '0',
  `status` varchar(16) NOT NULL DEFAULT '',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`email_campaign_adhoc_recipients_id`),
  KEY `email_address_campaign_id_idx` (`email_address_campaign_id`),
  KEY `update_date_idx` (`update_date`),
  KEY `email_address_process_locked_idx` (`email_campaign_schedule_id`,`status`,`locked_by_process`),
  KEY `email_address_campaign_process_locked_idx` (`email_campaign_id`,`status`,`locked_by_process`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_campaign_audience` (
  `email_campaign_audience_id` bigint unsigned NOT NULL DEFAULT '0',
  `parent_campaign_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'The ID of the campaign that is the basis for this audience',
  `staff_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'The ID of the admin who created the audience',
  `name` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The name of this audience',
  `where_clause` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'This or nonmember_where_clause must be specified (or both) - SQL clause for filtering members in audience. If not present, members are excluded',
  `nonmember_where_clause` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'This or where_clase must be specified (or both) - SQL clause for filtering non-members in audience. If not present, non-members are excluded',
  `where_attributes` longtext COLLATE utf8mb4_unicode_ci,
  `nonmember_where_attributes` longtext COLLATE utf8mb4_unicode_ci,
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'If true, the audience is hidden and no longer generated',
  `experiment_flag` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Feature flag used to bucket recipients into 2 schedules in Meteor',
  `before_hooks` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Comma separated list of hook-class names to be run before the send. Will override hooks defined on a campaign',
  `after_hooks` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Comma separated list of hook-class names to be run after the send. Will override hooks defined on a campaign',
  `status` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`email_campaign_audience_id`),
  KEY `deleted_idx` (`is_deleted`),
  KEY `status_idx` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8 COMMENT='a dynamic audience that can receive a meteor mailing';

CREATE TABLE `email_campaign_latest_sent_email_inspection` (
  `email_campaign_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_sent_email_inspection_id` bigint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`email_campaign_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPACT;

CREATE TABLE `email_campaign_process` (
  `email_campaign_process_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_schedule_id` bigint unsigned NOT NULL DEFAULT '0',
  `hostname` varchar(64) NOT NULL DEFAULT '',
  `system_process_id` int unsigned NOT NULL DEFAULT '0',
  `last_active_date` int unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`email_campaign_process_id`,`email_campaign_schedule_id`),
  KEY `last_active_date_idx` (`last_active_date`),
  KEY `hostname_idx` (`hostname`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_campaign_schedule` (
  `email_campaign_schedule_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_experiment_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_experiment_send_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_experiment_variant_id` bigint unsigned NOT NULL DEFAULT '0',
  `status` varchar(16) NOT NULL DEFAULT '',
  `before_send_hooks_executed` tinyint(1) NOT NULL DEFAULT '0',
  `after_send_hooks_executed` tinyint(1) NOT NULL DEFAULT '0',
  `second_half_seedlist_sent` tinyint(1) NOT NULL DEFAULT '0',
  `first_half_seedlist_sent` tinyint(1) NOT NULL DEFAULT '0',
  `name` varchar(256) NOT NULL DEFAULT '',
  `staff_id` bigint NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  `start_time` int unsigned DEFAULT NULL,
  `end_time` int unsigned DEFAULT NULL,
  `scheduled_so_far` int NOT NULL DEFAULT '0',
  `next_run` int unsigned NOT NULL DEFAULT '0',
  `email_address_campaign_contact_list_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_segment_id` bigint unsigned DEFAULT '0',
  `admin_test` tinyint(1) NOT NULL DEFAULT '0',
  `email_campaign_audience_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_address_audience_import_id` bigint unsigned DEFAULT NULL,
  `email_campaign_schedule_recurrence_id` bigint NOT NULL DEFAULT '0',
  `recipient_count` int unsigned DEFAULT NULL,
  `sent_count` int unsigned DEFAULT NULL,
  `job_status` varchar(16) NOT NULL DEFAULT '',
  PRIMARY KEY (`email_campaign_schedule_id`),
  KEY `name_campaign_id_idx` (`name`(255),`email_campaign_id`),
  KEY `email_experiment_id_idx` (`email_experiment_id`),
  KEY `update_date` (`update_date`),
  KEY `schedules_by_status_idx` (`status`,`email_campaign_id`,`next_run`),
  KEY `recurrence_id` (`email_campaign_schedule_recurrence_id`),
  KEY `email_experiment_send_id_idx` (`email_experiment_send_id`),
  KEY `campaign_id_create_date_idx` (`email_campaign_id`,`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_campaign_schedule_recurrence` (
  `email_campaign_schedule_recurrence_id` bigint unsigned NOT NULL,
  `email_campaign_audience_id` bigint unsigned NOT NULL,
  `day_of_week` tinyint unsigned NOT NULL,
  `time_of_day` smallint unsigned NOT NULL,
  `last_created_email_campaign_schedule_id` bigint unsigned DEFAULT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `first_send_date` int unsigned NOT NULL DEFAULT '0',
  `last_send_date` int unsigned DEFAULT NULL,
  `day_of_month` tinyint unsigned NOT NULL DEFAULT '0',
  `email_campaign_template_id` bigint unsigned NOT NULL DEFAULT '0',
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'confirmed',
  `name` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `is_variant` tinyint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`email_campaign_schedule_recurrence_id`),
  KEY `email_campaign_audience_index` (`email_campaign_audience_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPACT;

CREATE TABLE `email_campaign_segment` (
  `email_campaign_segment_id` bigint unsigned NOT NULL DEFAULT '0',
  `status` varchar(32) NOT NULL DEFAULT '',
  `name` varchar(100) NOT NULL DEFAULT '' COMMENT 'a-z and underscores',
  `segment_class` varchar(100) NOT NULL,
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`email_campaign_segment_id`),
  KEY `status_idx` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_campaign_sent_email_inspection` (
  `email_campaign_sent_email_inspection_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_template_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_schedule_id` bigint NOT NULL DEFAULT '0',
  `email_campaign_id` bigint unsigned NOT NULL DEFAULT '0',
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `user_id` bigint unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `subject` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `html_body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `campaign_label` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '',
  PRIMARY KEY (`email_campaign_sent_email_inspection_id`),
  KEY `create_date_campaign_label` (`create_date`,`campaign_label`),
  KEY `campaign_label` (`campaign_label`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_campaign_template` (
  `email_campaign_template_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_id` bigint unsigned NOT NULL DEFAULT '0',
  `position` int unsigned NOT NULL DEFAULT '0',
  `template_data` mediumtext,
  `status` varchar(32) NOT NULL DEFAULT '',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  `name` varchar(120) NOT NULL DEFAULT '',
  `utm_campaign` varchar(128) DEFAULT NULL,
  `email_campaign_schedule_id` bigint NOT NULL DEFAULT '0',
  `percent_split` float(5,2) DEFAULT NULL,
  `canvas_template_id` bigint DEFAULT NULL,
  `canvas_template_export_date` int unsigned DEFAULT NULL,
  `template_export_date` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`email_campaign_template_id`),
  KEY `email_campaign_id` (`email_campaign_id`),
  KEY `canvas_template_idx` (`canvas_template_id`),
  KEY `name_email_campaign_schedule_id_idx` (`name`,`email_campaign_schedule_id`),
  KEY `update_date` (`update_date`),
  KEY `email_campaign_schedule_id` (`email_campaign_schedule_id`,`status`),
  KEY `utm_campaign_idx` (`utm_campaign`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPACT;

CREATE TABLE `email_custora_uploads` (
  `email_custora_uploads_id` bigint unsigned NOT NULL DEFAULT '0',
  `template_id` varchar(255) NOT NULL DEFAULT '' COMMENT 'Unique template identifier: type-id (eg canvas-9001)',
  `status` varchar(15) DEFAULT NULL,
  `contents` longtext NOT NULL,
  `create_date` int unsigned DEFAULT NULL,
  `update_date` int unsigned DEFAULT NULL,
  `email_campaign_schedule_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`email_custora_uploads_id`),
  KEY `template_id_idx` (`template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8 COMMENT='Holding cell for Custora subscriber lists';

CREATE TABLE `email_experiment_sends` (
  `email_experiment_send_id` bigint unsigned NOT NULL,
  `email_experiment_id` bigint unsigned NOT NULL,
  `email_address_audience_import_id` bigint unsigned NOT NULL DEFAULT '0',
  `send_date` int unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`email_experiment_send_id`),
  UNIQUE KEY `unique_experiment_date_idx` (`send_date`,`email_experiment_id`),
  KEY `email_experiment_id_idx` (`email_experiment_id`),
  KEY `create_date_idx` (`create_date`),
  KEY `update_date_idx` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_experiment_variants` (
  `email_experiment_variant_id` bigint unsigned NOT NULL,
  `email_experiment_id` bigint unsigned NOT NULL,
  `variant_bucket` varchar(75) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The variant bucket per the config, e.g. off or on',
  `variant_name` varchar(75) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Human-readable variant name, e.g. Control or Variant',
  `variant_description` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Description of the variant',
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  PRIMARY KEY (`email_experiment_variant_id`),
  UNIQUE KEY `experiment_bucket` (`email_experiment_id`,`variant_bucket`),
  KEY `create_date_idx` (`create_date`),
  KEY `update_date_idx` (`update_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_experiments` (
  `email_experiment_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_audience_id` bigint unsigned NOT NULL DEFAULT '0',
  `status` varchar(32) NOT NULL DEFAULT '',
  `name` varchar(100) NOT NULL DEFAULT '',
  `test_type` varchar(20) NOT NULL DEFAULT '',
  `notes` text NOT NULL,
  `variant_percent` tinyint unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  `config_key` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`email_experiment_id`),
  KEY `status_idx` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_recipient_import` (
  `raw_line` text NOT NULL,
  `status` varchar(255) DEFAULT NULL,
  `email_recipient_import_metadata_id` bigint unsigned NOT NULL DEFAULT '0',
  `create_date` int unsigned NOT NULL DEFAULT '0',
  `update_date` int unsigned NOT NULL DEFAULT '0',
  `email_recipient_import_line_number` bigint NOT NULL DEFAULT '0',
  `locked_by_process` varchar(64) NOT NULL DEFAULT '',
  PRIMARY KEY (`email_recipient_import_line_number`,`email_recipient_import_metadata_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf16 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_recipient_import_metadata` (
  `email_recipient_import_metadata_id` bigint unsigned NOT NULL,
  `email_campaign_id` bigint unsigned NOT NULL DEFAULT '0',
  `email_campaign_schedule_id` bigint unsigned DEFAULT '0',
  `import_type` varchar(255) NOT NULL DEFAULT '',
  `import_date` int unsigned NOT NULL DEFAULT '0',
  `import_status` varchar(255) NOT NULL DEFAULT '',
  `import_filename` varchar(255) NOT NULL DEFAULT '',
  `expected_subscriber_import_count` mediumint unsigned NOT NULL DEFAULT '0',
  `actual_subscriber_import_count` mediumint unsigned NOT NULL DEFAULT '0',
  `addresses_already_subscribed_count` mediumint unsigned NOT NULL DEFAULT '0',
  `addresses_in_db_count` mediumint unsigned NOT NULL DEFAULT '0',
  `addresses_not_in_db_count` mediumint unsigned NOT NULL DEFAULT '0',
  `addresses_not_subscribed_count` mediumint unsigned NOT NULL DEFAULT '0',
  `no_user_record_count` mediumint unsigned NOT NULL DEFAULT '0',
  `invalid_line_count` mediumint unsigned NOT NULL DEFAULT '0',
  `header_line` text NOT NULL,
  `addresses_not_confirmed_count` mediumint unsigned NOT NULL DEFAULT '0',
  `addresses_unreliable_count` mediumint unsigned NOT NULL DEFAULT '0',
  `email_address_campaign_contact_list_id` bigint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`email_recipient_import_metadata_id`),
  KEY `email_campaign_id` (`email_campaign_id`),
  KEY `email_campaign_schedule_id` (`email_campaign_schedule_id`),
  KEY `import_status` (`import_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_user_segments` (
  `user_id` bigint unsigned NOT NULL,
  `email_id` bigint unsigned NOT NULL,
  `country_id` bigint unsigned DEFAULT NULL,
  `language` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `registration_date` int unsigned DEFAULT NULL,
  `email_domain` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_state` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_etsy_finds` tinyint unsigned DEFAULT NULL,
  `is_etsy_success` tinyint unsigned DEFAULT NULL,
  `is_craft_buyer_prospects` tinyint unsigned DEFAULT NULL,
  `last_visit_date` int unsigned DEFAULT NULL,
  `order_count` int DEFAULT NULL,
  `top_purchase_country_id` bigint unsigned DEFAULT NULL,
  `at_risk` tinyint unsigned DEFAULT NULL,
  `ltv_decile` int DEFAULT NULL,
  `latest_zip` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `default_shipping_country_id` int DEFAULT NULL,
  `shipping_country_id_1` int DEFAULT NULL,
  `shipping_country_id_2` int DEFAULT NULL,
  `shipping_country_id_3` int DEFAULT NULL,
  `shipping_country_id_4` int DEFAULT NULL,
  `shipping_country_id_5` int DEFAULT NULL,
  `default_shipping_zip` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipping_zip_1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipping_zip_2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipping_zip_3` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipping_zip_4` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipping_zip_5` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buyer_app_visits` int DEFAULT NULL,
  `seller_app_visits` int DEFAULT NULL,
  `tablet_web_visits` int DEFAULT NULL,
  `mobile_web_visits` int DEFAULT NULL,
  `desktop_web_visits` int DEFAULT NULL,
  `latest_click` int unsigned DEFAULT NULL,
  `latest_open` int unsigned DEFAULT NULL,
  `aov` float DEFAULT NULL,
  `first_purchase_date` int unsigned DEFAULT NULL,
  `first_purchase_root_taxonomy_id` bigint unsigned DEFAULT NULL,
  `first_purchase_sub_root_taxonomy_id` bigint unsigned DEFAULT NULL,
  `last_purchase_date` int unsigned DEFAULT NULL,
  `last_purchase_root_taxonomy_id` bigint unsigned DEFAULT NULL,
  `last_purchase_sub_root_taxonomy_id` bigint unsigned DEFAULT NULL,
  `recommended_root_taxonomy_id_1` bigint unsigned DEFAULT NULL,
  `recommended_sub_root_taxonomy_id_1` bigint unsigned DEFAULT NULL,
  `favorites` int DEFAULT NULL,
  `favorite_root_taxonomy_id_1_30d` bigint unsigned DEFAULT NULL,
  `favorite_root_taxonomy_id_1_90d` bigint unsigned DEFAULT NULL,
  `favorite_root_taxonomy_id_1_180d` bigint unsigned DEFAULT NULL,
  `favorite_sub_root_taxonomy_id_1_30d` bigint unsigned DEFAULT NULL,
  `favorite_sub_root_taxonomy_id_1_90d` bigint unsigned DEFAULT NULL,
  `favorite_sub_root_taxonomy_id_1_180d` bigint unsigned DEFAULT NULL,
  `browse_root_taxonomy_id_1_30d` bigint unsigned DEFAULT NULL,
  `browse_root_taxonomy_id_1_90d` bigint unsigned DEFAULT NULL,
  `browse_root_taxonomy_id_1_180d` bigint unsigned DEFAULT NULL,
  `browse_sub_root_taxonomy_id_1_30d` bigint unsigned DEFAULT NULL,
  `browse_sub_root_taxonomy_id_1_90d` bigint unsigned DEFAULT NULL,
  `browse_sub_root_taxonomy_id_1_180d` bigint unsigned DEFAULT NULL,
  `purchase_root_taxonomy_id_1` bigint unsigned DEFAULT NULL,
  `purchase_root_taxonomy_id_1_30d` bigint unsigned DEFAULT NULL,
  `purchase_root_taxonomy_id_1_90d` bigint unsigned DEFAULT NULL,
  `purchase_root_taxonomy_id_1_180d` bigint unsigned DEFAULT NULL,
  `purchase_sub_root_taxonomy_id_1` bigint unsigned DEFAULT NULL,
  `purchase_sub_root_taxonomy_id_1_30d` bigint unsigned DEFAULT NULL,
  `purchase_sub_root_taxonomy_id_1_90d` bigint unsigned DEFAULT NULL,
  `purchase_sub_root_taxonomy_id_1_180d` bigint unsigned DEFAULT NULL,
  `listing_views_180d` int DEFAULT NULL,
  `has_seller_advisor` tinyint unsigned DEFAULT NULL,
  `shop_initial_seller_type` int DEFAULT NULL,
  `prolist_current_start_date` int unsigned DEFAULT NULL,
  `prolist_is_active` tinyint unsigned DEFAULT NULL,
  `prolist_ever_active` tinyint unsigned DEFAULT NULL,
  `shop_uses_shipping_labels` tinyint unsigned DEFAULT NULL,
  `is_nipsa` tinyint unsigned DEFAULT NULL,
  `is_seller` tinyint unsigned DEFAULT NULL,
  `is_active_seller` tinyint unsigned DEFAULT NULL,
  `shop_status` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `allows_direct_checkout` tinyint unsigned DEFAULT NULL,
  `shop_billing_country_id` bigint unsigned DEFAULT NULL,
  `shop_last_listing_date` int unsigned DEFAULT NULL,
  `shop_last_sale_date` int unsigned DEFAULT NULL,
  `shop_create_date` int unsigned DEFAULT NULL,
  `shop_open_date` int unsigned DEFAULT NULL,
  `shop_active_listings` int DEFAULT NULL,
  `shop_sales` int DEFAULT NULL,
  `shop_orders` int DEFAULT NULL,
  `shop_gms_last_year` float DEFAULT NULL,
  `shop_gms` float DEFAULT NULL,
  `wholesale_vendor_state` int DEFAULT NULL,
  `nonmember_region` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nonmember_language` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buyer_segment` tinyint(1) DEFAULT NULL,
  `buyer_segment_name` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`user_id`,`email_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `email_user_segments__last` (
  `user_id` bigint unsigned NOT NULL,
  `email_id` bigint unsigned NOT NULL,
  `country_id` bigint unsigned DEFAULT NULL,
  `language` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `registration_date` int unsigned DEFAULT NULL,
  `email_domain` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_state` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_etsy_finds` tinyint unsigned DEFAULT NULL,
  `is_etsy_success` tinyint unsigned DEFAULT NULL,
  `is_craft_buyer_prospects` tinyint unsigned DEFAULT NULL,
  `last_visit_date` int unsigned DEFAULT NULL,
  `order_count` int DEFAULT NULL,
  `top_purchase_country_id` bigint unsigned DEFAULT NULL,
  `at_risk` tinyint unsigned DEFAULT NULL,
  `ltv_decile` int DEFAULT NULL,
  `latest_zip` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `default_shipping_country_id` int DEFAULT NULL,
  `shipping_country_id_1` int DEFAULT NULL,
  `shipping_country_id_2` int DEFAULT NULL,
  `shipping_country_id_3` int DEFAULT NULL,
  `shipping_country_id_4` int DEFAULT NULL,
  `shipping_country_id_5` int DEFAULT NULL,
  `default_shipping_zip` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipping_zip_1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipping_zip_2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipping_zip_3` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipping_zip_4` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipping_zip_5` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buyer_app_visits` int DEFAULT NULL,
  `seller_app_visits` int DEFAULT NULL,
  `tablet_web_visits` int DEFAULT NULL,
  `mobile_web_visits` int DEFAULT NULL,
  `desktop_web_visits` int DEFAULT NULL,
  `latest_click` int unsigned DEFAULT NULL,
  `latest_open` int unsigned DEFAULT NULL,
  `aov` float DEFAULT NULL,
  `first_purchase_date` int unsigned DEFAULT NULL,
  `first_purchase_root_taxonomy_id` bigint unsigned DEFAULT NULL,
  `first_purchase_sub_root_taxonomy_id` bigint unsigned DEFAULT NULL,
  `last_purchase_date` int unsigned DEFAULT NULL,
  `last_purchase_root_taxonomy_id` bigint unsigned DEFAULT NULL,
  `last_purchase_sub_root_taxonomy_id` bigint unsigned DEFAULT NULL,
  `recommended_root_taxonomy_id_1` bigint unsigned DEFAULT NULL,
  `recommended_sub_root_taxonomy_id_1` bigint unsigned DEFAULT NULL,
  `favorites` int DEFAULT NULL,
  `favorite_root_taxonomy_id_1_30d` bigint unsigned DEFAULT NULL,
  `favorite_root_taxonomy_id_1_90d` bigint unsigned DEFAULT NULL,
  `favorite_root_taxonomy_id_1_180d` bigint unsigned DEFAULT NULL,
  `favorite_sub_root_taxonomy_id_1_30d` bigint unsigned DEFAULT NULL,
  `favorite_sub_root_taxonomy_id_1_90d` bigint unsigned DEFAULT NULL,
  `favorite_sub_root_taxonomy_id_1_180d` bigint unsigned DEFAULT NULL,
  `browse_root_taxonomy_id_1_30d` bigint unsigned DEFAULT NULL,
  `browse_root_taxonomy_id_1_90d` bigint unsigned DEFAULT NULL,
  `browse_root_taxonomy_id_1_180d` bigint unsigned DEFAULT NULL,
  `browse_sub_root_taxonomy_id_1_30d` bigint unsigned DEFAULT NULL,
  `browse_sub_root_taxonomy_id_1_90d` bigint unsigned DEFAULT NULL,
  `browse_sub_root_taxonomy_id_1_180d` bigint unsigned DEFAULT NULL,
  `purchase_root_taxonomy_id_1` bigint unsigned DEFAULT NULL,
  `purchase_root_taxonomy_id_1_30d` bigint unsigned DEFAULT NULL,
  `purchase_root_taxonomy_id_1_90d` bigint unsigned DEFAULT NULL,
  `purchase_root_taxonomy_id_1_180d` bigint unsigned DEFAULT NULL,
  `purchase_sub_root_taxonomy_id_1` bigint unsigned DEFAULT NULL,
  `purchase_sub_root_taxonomy_id_1_30d` bigint unsigned DEFAULT NULL,
  `purchase_sub_root_taxonomy_id_1_90d` bigint unsigned DEFAULT NULL,
  `purchase_sub_root_taxonomy_id_1_180d` bigint unsigned DEFAULT NULL,
  `listing_views_180d` int DEFAULT NULL,
  `has_seller_advisor` tinyint unsigned DEFAULT NULL,
  `shop_initial_seller_type` int DEFAULT NULL,
  `prolist_current_start_date` int unsigned DEFAULT NULL,
  `prolist_is_active` tinyint unsigned DEFAULT NULL,
  `prolist_ever_active` tinyint unsigned DEFAULT NULL,
  `shop_uses_shipping_labels` tinyint unsigned DEFAULT NULL,
  `is_nipsa` tinyint unsigned DEFAULT NULL,
  `is_seller` tinyint unsigned DEFAULT NULL,
  `is_active_seller` tinyint unsigned DEFAULT NULL,
  `shop_status` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `allows_direct_checkout` tinyint unsigned DEFAULT NULL,
  `shop_billing_country_id` bigint unsigned DEFAULT NULL,
  `shop_last_listing_date` int unsigned DEFAULT NULL,
  `shop_last_sale_date` int unsigned DEFAULT NULL,
  `shop_create_date` int unsigned DEFAULT NULL,
  `shop_open_date` int unsigned DEFAULT NULL,
  `shop_active_listings` int DEFAULT NULL,
  `shop_sales` int DEFAULT NULL,
  `shop_orders` int DEFAULT NULL,
  `shop_gms_last_year` float DEFAULT NULL,
  `shop_gms` float DEFAULT NULL,
  `wholesale_vendor_state` int DEFAULT NULL,
  `nonmember_region` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nonmember_language` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buyer_segment` tinyint(1) DEFAULT NULL,
  `buyer_segment_name` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`user_id`,`email_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE `triggered_notifications_cursor` (
  `cursor_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'generic',
  `last_run_at` int unsigned NOT NULL COMMENT 'timestamp of the last time a triggered_notification cron was run',
  PRIMARY KEY (`cursor_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPACT;

CREATE TABLE `vitess_etet` (
  `id` bigint unsigned NOT NULL,
  `create_date` int unsigned NOT NULL,
  `update_date` int unsigned NOT NULL,
  `f_varchar` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

